#!/bin/bash
#This shebang is for synax only. Do not make executable!

export BORG=$(cat ~/.local/var/myborg/current.txt)

echo . ${BORG}/handler $*
source ${BORG}/first
source ${BORG}/dotfiles/$1
source ${BORG}/last
