#!/bin/bash
#This shebang is for synax only. Do not make executable!

export BORG=$(cat ~/.local/var/myborg/current.txt)

echo . ${BORG}/dothandler $*

[ -z "$BORG_INIT" ] && {
    echo . ${BORG}/init
    source ${BORG}/init
}

echo . \${BORG}/dotfiles/$*
source ${BORG}/dotfiles/$*

echo ENTER LEVEL $(( ${SHLVL} - 1 ))
trap "echo ENTER LEVEL $(( ${SHLVL} - 2 ))" 0

