#!/bin/bash


_trace () {
    local acc=
    local part=
    for ii in $(seq $1 $2); do
        part=${FUNCNAME[${ii}]}
        [ -z "${part}" ] && break
        [ "${part}" = "source" ] && [ "$3" = "--ignore-source" ] && break
        acc="[${part}]>>$acc"
    done
    echo ">>$acc"
}

_github () {
    local src=http://github.com/$1
    local dst=${BORG}/.repo/github/$1
    [ -d ${dst} ] || git clone $src $dst 2> /dev/null > /dev/null
    [ -d ${dst} ] && echo ${dst}
    [ -d ${dst} ] && return 0
    return 1
}

_banner () {
    banner=">>>>>>>>>>>>>>>>[$1]"
    #delay=$3
    [ -z "${delay}" ] && delay=0
    printf "${banner} "
    for ii in 3 2 1; do
        printf "."
        [ -z $3 ] || sleep $3
    done
    printf "$2\n"
}

_log () {
  echo "$(_trace 1 8 --ignore-source)" $*
}

_run () {
  echo $(_trace 1 8 --ignore-source) $*
  $*
}

_short () {
  echo $(basename $(dirname $1))/$(basename $1)
}

_source () {
  _log $(_short $1)
  source $*
}

_source_all () {
  for f in $(ls -1 ${1}/[0-9][0-9][0-9]*); do
    _source $f
  done
}

_source_once () {
  [ -z ${BORG_FLAG_RUNONCE} ] && {
    export BORG_FLAG_RUNONCE=1
    _log running: $(_short $1)
    _source $1
  } || {
    _log skipping: $(_short $1)
  }
}
