#!/bin/bash
#This shebang is for synax only. Do not make executable!

borg_relpath () {
    [ -f /usr/bin/realpath ] \
    && echo ./$( realpath --relative-to ${BORG} ${1} ) \
    || echo $1
}

borg_source () {
    echo . $(borg_relpath $1)
    . $1
}
