#!/bin/bash
cat >/dev/null<<END_DOCUMENTATION

+-------------------------------------------+
!  The  borg_* library of bash functions  !
+-------------------------------------------+

This is a library of function that all begin with the string 
[borg_]. No function outside this library should be so 
named. All functions of this library shall be available to
scripts that are installing the full system. They are not
meant to be used by scripts used after the full system is
installed.

All of these functions shall be defined in misc files that
are named

    NNN.some-description

where 'NNN' is a string of three digits, and 'some description'
indicates what functions(s) are defined within. In general the
description will be then name of the function itself, or some
prefix of several functions contained therein. The files will
be sourced in ascending numerical order. Functions defined in
file '500.foo' will be able to call functions defined in file
'400.foo' but not functions defined in '600.foo'

The only exception to this is the function defined herein 
named 'borg_source_all' whose purpose is to source the
others.

There is no need for the sourcer of this library to actually
use this function to load the rest of the library. This script
will do it in it's final line. Nonetheless this function may
be useful to other scripts to source additional libraries.

END_DOCUMENTATION

############################################################
# Pass this function a path to a directory. It will source
# all files that begin with a digit.
#
# It is meant to be used when the directory contains files
# named like this:

#   010.the-first-file
#   100.the-second-file
#
# The files will be sourced *in that order*.
# to insure the automatic
############################################################
borg_source_all () {
    printf "Loading from from $(basename $1):"
    for f in $(ls -1 ${1}/[0-9][0-9][0-9]*); do 
        >&2 printf " [$(basename $f)]"
        source $f
    done
    printf ".\n"
}


borg() {
  borg_$*
}

borg_ () {
  compgen -A function | grep "borg_"
}
borg_source_all ${BORG}/lib-borg
echo "For help type 'borg'."
